spring.application.name=sb-ecom

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=guest

spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

project.image=images/


spring.app.jwtSecret=mySecretKey123912738jsdnvsnfveimkasmscsmcaldkvnjfnbionienvieqiefmo
spring.app.jwtExpirationMs=86400000
spring.ecom.app.jwtCookie=springBootEcom


#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG


